# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Canning Road"
#url: "https://stegriff.github.io/canning-road-jekyll/"
url: http://stegriff.co.uk/test/canning-road/
permalink: /post/:title/
collections:
 services:
  output : true
 activities:
  output : true

defaults:
  -
    scope:
      path: "" # All files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      has_pager: true

gems:
  - jekyll-optional-front-matter
  - jekyll-default-layout
exclude:
  - Gemfile
  - Gemfile.lock
