# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

url: "localhost"
twitter_username: stegriff
github_username:  stegriff
permalink: /:title/
collections:
 services:
  output : true
 activities:
  output : true

defaults:
  -
    scope:
      path: "" # All files in the project
    values:
      layout: "default"

gems:
  - jekyll-optional-front-matter
  - jekyll-default-layout
exclude:
  - Gemfile
  - Gemfile.lock
