# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Canning Road"

# This is an unusual way to configure jekyll but I'm running with it
# Must have a slash / at the end:
url: https://stegriff.github.io/canning-road-jekyll/

# Simple permalinks with no dates
permalink: /post/:title/

# Define our collections (output means they get their own pages too)
collections:
 services:
  output : true
 activities:
  output : true

# Set default.html as default layout, and set has_pager on all bloggy posts
defaults:
  -
    scope:
      path: "" # All files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      has_pager: true

# Includes
gems:
  - jekyll-optional-front-matter
  - jekyll-default-layout
exclude:
  - Gemfile
  - Gemfile.lock
